containerSetup: &containerSetup
  docker:
    - image: cimg/openjdk:15.0.1
    - image: swaggerapi/petstore3:unstable
  environment:
    ENV: circle
  working_directory: ~/repo

version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/build.gradle" }}
            - v1-dependencies-

      - run:
          name: Gradle Dependencies
          command: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "app/build.gradle" }}

      - persist_to_workspace:
          root: .
          paths:
            - gradle

  sanityTests:
    <<: *containerSetup
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/build.gradle" }}
      - run:
          name: Debug Test Results Directory
          command: ls -R app/build/test-results/test
      - run:
          name: Sanity Tests
          command: gradle sanityTest
          when: always
      - store_test_results:
          path: app/build/test-results/test
      - store_artifacts:
          path: app/build/reports

  regressionTests:
    <<: *containerSetup
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/build.gradle" }}
      - run:
          name: Regression Tests
          command: gradle test --info
          when: always
      - store_test_results:
          path: app/build/test-results/test
      - store_artifacts:
          path: app/build/reports

workflows:
  version: 2
  qe-api:
    jobs:
      - build
      - sanityTests:
          requires:
            - build
          steps:
            - run:
                name: Debug Test Results Directory
                command: ls -R app/build/test-results/test
