version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:15.0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Setup Gradle
      - run:
          name: Setup Gradle
          command: |
            sudo apt-get update && sudo apt-get install -y wget unzip
            wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
            unzip -d /opt/gradle gradle-8.6-bin.zip
            export PATH=$PATH:/opt/gradle/gradle-8.6/bin

      # Restore cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      # Download dependencies
      - run:
          name: Download Dependencies
          command: gradle dependencies --no-daemon

      # Save dependencies to cache
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Run tests
      - run:
          name: Run Tests
          command: gradle test --stacktrace

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test