version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:15.0.1

    steps:
      - checkout

      - run:
          name: Setup Gradle
          command: |
            curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.6-bin.zip
            unzip -d /opt/gradle gradle.zip
            export PATH=$PATH:/opt/gradle/gradle-8.6/bin

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Gradle Dependencies
          command: gradle dependencies --no-daemon

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - persist_to_workspace:
          root: .
          paths:
            - gradle

  sanityTests:
    docker:
      - image: openjdk:15.0.1

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Sanity Tests
          command: gradle sanityTest
          when: always
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports

  regressionTests:
    docker:
      - image: openjdk:15.0.1

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Regression Tests
          command: gradle test
          when: always

workflows:
  version: 2
  qaops-bdd:
    jobs:
      - build
      - sanityTests:
          requires:
            - build
      - regressionTests:
          requires:
            - build