version: 2.1

jobs:
  build-and-test:
    docker:
      - image: openjdk:15.0.1
    steps:
      - checkout
      - run:
          name: Setup Gradle
          command: |
            apt-get update && apt-get install -y wget unzip
            wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
            unzip -d /opt/gradle gradle-8.6-bin.zip
            export PATH=$PATH:/opt/gradle/gradle-8.6/bin
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Gradle Dependencies
          command: gradle dependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Gradle Build and Test
          command: gradle test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test