version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:15.0.1

    steps:
      - checkout

      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      - run:
          name: Gradle Dependencies
          command: ./gradlew dependencies --no-daemon

      - persist_to_workspace:
          root: .
          paths:
            - .gradle

  sanityTests:
    docker:
      - image: openjdk:15.0.1

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Sanity Tests
          command: ./gradlew sanityTest
          when: always

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports

  regressionTests:
    docker:
      - image: openjdk:15.0.1

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Regression Tests
          command: ./gradlew test
          when: always

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports

workflows:
  version: 2
  qe-sicredi:
    jobs:
      - build
      - sanityTests:
          requires:
            - build
      - regressionTests:
          requires:
            - sanityTests